name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Ruby ${{ matrix.ruby }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
        trilogy:
          - '2.0.0'
          - '2.1.0'
          - '2.2.0'
          - '2.3.0'
          - '2.4.0'
          - '2.5.0'
          - '2.6.0'

    env:
      RUBY_VERSION: ${{ matrix.ruby }}
      TRILOGY_VERSION: ${{ matrix.trilogy }}

    steps:
    - uses: actions/checkout@v3
    - name: Docker Build
      run: docker-compose build --build-arg RUBY_VERSION=$RUBY_VERSION TRILOGY_VERSION=$TRILOGY_VERSION
    - name: Docker MySQL Healthcheck
      run: docker-compose run --rm app echo "MySQL Healthy"
    - name: Check trilogy version
      run: docker-compose run --rm app bundle info trilogy
    - name: Run tests with Docker
      run: docker-compose run --rm app ./bin/test

  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Rubocop
      run: bundle exec rake rubocop
