name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Test Ruby ${{ matrix.ruby }} with Trilogy ${{ matrix.trilogy }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3"
          - "3.4"
        trilogy:
          - "2.5"
          - "2.6"
          - "2.7"
          - "2.8"
          - "2.9"

    env:
      TRILOGY_VERSION: ${{ matrix.trilogy }}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ./.github/actions/setup-mysql
      - run: bundle exec rake spec

  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rake rubocop
