name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Ruby ${{ matrix.ruby }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'

    env:
      RUBY_VERSION: ${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v3
    - name: Docker Build
      run: docker-compose build --build-arg RUBY_VERSION=$RUBY_VERSION
    - name: Run tests with Docker
      run: docker-compose run --rm app ./bin/test

  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Rubocop
      run: bundle exec rake rubocop
